cargo-features = ["profile-rustflags"]

[package]
name = "count_ones"
version = "0.1.0"
edition = "2021"


[dependencies]
lazy_static = "1.4.0"
rand = "0.8.5"

[build]
rustflags = ["-C target-cpu=native"]

[profile.dev]
opt-level = 3